Доп правило
htmlacademy/eslint-config-htmlacademy pull request #42
Opened 2019-12-17 18:46 UTC by SlavaMilin

2019-12-18 06:33 UTC, SlavaMilin commented
Да вроде не должно. На сервере я смотрю сейчас стоит версия eslint 6.5.1. Пониже сделать?

2019-12-18 06:36 UTC, SlavaMilin commented
Тем более чтобы принялись изменения у студентов им надо будет поднять версию конфига

2019-12-18 07:42 UTC, sashasushko commented
Нет, мы не можем просить студентов что-то делать у себя. Версии должны быть одинаковые

2019-12-18 07:45 UTC, sashasushko commented
Вот версия, которая была в Гоше для студентов - https://github.com/htmlacademy/intensive-objects/blob/feature/update-spec-task-manager/gosha/cinemaddict/init/package.json

2019-12-18 07:45 UTC, sashasushko commented
Значит поверка у нас должна быть под эту же версию

2019-12-18 07:49 UTC, SlavaMilin commented
Не, я к тому, что вы можете на следующий поток поднять версию линтера и конфига.

2019-12-18 08:01 UTC, sashasushko commented
Ааа, это - да.

2019-12-18 08:03 UTC, SlavaMilin commented
Окей, я пока оставлю pr, я вижу ещё пару правил, которые могут закрыть критерии, после отпуска дёрну вас ещё раз.

2021-02-02 10:39 UTC, kam4atka commented
Task - https://app.clickup.com/t/crxrpb

2021-02-03 11:01 UTC, sashasushko requested changes
Нужно принять саджесты и можно мёржить

2021-02-03 11:01 UTC, sashasushko commented on vanilla.js
> +    'prefer-const': `error`,
```suggestion
    'prefer-const': 'error',
```

2021-02-03 11:01 UTC, sashasushko commented on vanilla.js
>      'no-var': ['error'],
Заодно тогда
```suggestion
    'no-var': 'error',
```

2021-02-03 14:00 UTC, merged