Added  eslint:recommended config
htmlacademy/eslint-config-htmlacademy pull request #43
Opened 2020-12-23 14:23 UTC by kam4atka

- added eslint:recommended config
- added no-console rule
- added comma-dangle rule (always-multiline for objects, arrays and functions)
- added indent rule (2 spaces always)
- added quotes rule (singlequote & backtick)
- added no-var rule

2020-12-25 08:52 UTC, kam4atka commented
Task - https://app.clickup.com/t/aq15cn

2020-12-25 14:12 UTC, sashasushko reviewed
Не могу понять, а как тесты работают? Почему там только валидные примеры? Ты не разбирался, @kam4atka?

2020-12-25 14:18 UTC, kam4atka commented
> Не могу понять, а как тесты работают? Почему там только валидные примеры? Ты не разбирался, @kam4atka?

Они работают отрабатывают если написать не валидный пример.
Если ошибок нет, то все ок.

2020-12-25 14:26 UTC, kam4atka commented
Если подробнее то, в каждой директории test свой
- .estlintrc c дополнительными настройками, которые будут использоваться в проектах
- eslint.js с правилами, дублирующими правила из корня
Они распространяются локально на директорию в которой лежат (если нужно, то экспортируют дополнительно правила).
Если написать некорректный код, то VSCode или npm test выводят ошибки..

Но там нужно еще смотреть на вывод самого ESLint. Я долго думал почему у меня некоторые правила не тестируются, а потом оказалось что он не мог какой то конфиг загрузить.. Или, например, пришлось местами поменять экспорт конфигов (в es6.js) потому что правила es5 переписывали es6..

2020-12-25 14:41 UTC, sashasushko commented
Ладно, надо будет ещё покопать, на кой это всё нужно.

2020-12-25 14:41 UTC, sashasushko approved these changes

2021-01-18 14:17 UTC, sashasushko requested changes
~Нужно отдельным коммитом в ветку добавить изменения в changelog и поднять версию пакета в package.json до 1.0.0~

2021-01-18 14:18 UTC, sashasushko approved these changes

2021-01-18 14:18 UTC, merged