Доработка конфигурационного файла
htmlacademy/eslint-config-htmlacademy pull request #49
Opened 2021-03-18 17:01 UTC by kam4atka

2021-03-19 12:03 UTC, sashasushko requested changes

2021-03-19 12:03 UTC, sashasushko commented on test/vanilla/prefer-arrow-callback.js
> +func0(a => a);
@kam4atka нам нужно ещё правило, которое обяжет ставить круглые скобки в стрелках даже для одного параметра

2021-03-19 12:03 UTC, sashasushko commented on vanilla.js
> +    'no-multiple-empty-lines': 'error',
Тут нужно разрешить не более двух пустых строк подряд. Иногда две помогают отделять по смыслу. Больше уже перебор

2021-03-19 12:22 UTC, kam4atka commented on vanilla.js
> +    'no-multiple-empty-lines': 'error',
Я оставил значение `error` потому что у данного правила две пустые строки по дефолту идут.

> "max" (default: 2) enforces a maximum number of consecutive empty lines.

2021-03-19 13:17 UTC, kam4atka commented on test/vanilla/prefer-arrow-callback.js
> +func0(a => a);
Добавил правило [arrow-parens](https://eslint.org/docs/rules/arrow-parens)

2021-03-19 15:39 UTC, sashasushko approved these changes
Апрув. Можно лить, но пока не релизить. Нужно поставить две задачи: одну на Игоря, чтобы разработать правила для React; вторую на тебя, чтобы после добавления правил по Реакт, релизнуть 3.0.0

2021-03-22 13:23 UTC, sashasushko approved these changes

2021-03-22 13:26 UTC, merged